<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="pack_one.demo_one" tests="2" time="1.034" ignored="0" failures="0" timestamp="02 Jun 2017 09:45:02 GMT" skipped="0" hostname="SNYCON-PC" errors="1">
  <testcase name="secondTestCase" time="0.009" classname="pack_one.demo_one"/>
  <testcase name="firstTestCase" time="1.025" classname="pack_one.demo_one">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method pack_one.demo_one.firstTestCase() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method pack_one.demo_one.firstTestCase() didn't finish within the time-out 1000
]]>
    </error>
  </testcase> <!-- firstTestCase -->
</testsuite> <!-- pack_one.demo_one -->
